//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SICIApp.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONDICIONFISICA_INGRESO
    {
        public int IDINGRESO { get; set; }
        public Nullable<bool> PADECE { get; set; }
        public string DETALLE { get; set; }
        public Nullable<bool> RECIBIOTRATAMIENTO { get; set; }
        public Nullable<bool> TIENEIMPEDIMENTOS { get; set; }
        public Nullable<bool> DUERMEBIEN { get; set; }
        public Nullable<bool> PADECENERVIOS { get; set; }
        public Nullable<bool> HASIDOOPERADO { get; set; }
        public string ONSERVACIONESGENERALES { get; set; }
        public Nullable<System.DateTime> FECHADIAGNOSTICO { get; set; }
    
        public virtual INGRESO INGRESO { get; set; }
    }
}
