//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SICIApp.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONDICIONFISICA_INTERNOENFERMEDADES
    {
        public int ID { get; set; }
        public Nullable<int> IDINGRESO { get; set; }
        public Nullable<int> IDENFERMEDAD { get; set; }
    
        public virtual CONDICIONFISICA_ENFERMEDADES CONDICIONFISICA_ENFERMEDADES { get; set; }
        public virtual INGRESO INGRESO { get; set; }
    }
}
