//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SICIApp.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONT_MES
    {
        public CONT_MES()
        {
            this.CONT_CODOTALONARIO = new HashSet<CONT_CODOTALONARIO>();
        }
    
        public int ID { get; set; }
        public string NOMBREMES { get; set; }
        public Nullable<System.DateTime> FECHAINICIO { get; set; }
        public Nullable<System.DateTime> FECHACIERRE { get; set; }
        public Nullable<System.DateTime> FECHACORTE { get; set; }
        public string DESCRIPCION { get; set; }
    
        public virtual ICollection<CONT_CODOTALONARIO> CONT_CODOTALONARIO { get; set; }
    }
}
