//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SICIApp.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONT_FACTURA
    {
        public int ID { get; set; }
        public string NUMEROENFISICO { get; set; }
        public Nullable<System.DateTime> FECHACREACION { get; set; }
        public Nullable<decimal> VALORPAGADO { get; set; }
        public string DESCRIPCION { get; set; }
        public string ESTADO { get; set; }
        public string ARCHIVO { get; set; }
        public Nullable<int> IDCODO { get; set; }
    
        public virtual CONT_CODOTALONARIO CONT_CODOTALONARIO { get; set; }
    }
}
