//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SICIApp.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONT_CODOTALONARIO
    {
        public CONT_CODOTALONARIO()
        {
            this.CONT_FACTURA = new HashSet<CONT_FACTURA>();
        }
    
        public int ID { get; set; }
        public Nullable<System.DateTime> FECHACREADO { get; set; }
        public Nullable<System.DateTime> FECHAAPAGAR { get; set; }
        public Nullable<System.DateTime> FECHAPAGO { get; set; }
        public Nullable<decimal> VALORAPAGAR { get; set; }
        public string DESCRIPCION { get; set; }
        public Nullable<int> IDTALONARIO { get; set; }
        public Nullable<int> IDMES { get; set; }
        public Nullable<int> IDTIPOCONCEPTO { get; set; }
        public Nullable<int> IDTIPOESTADO { get; set; }
    
        public virtual CONT_ESTADOPAGO CONT_ESTADOPAGO { get; set; }
        public virtual CONT_MES CONT_MES { get; set; }
        public virtual CONT_TALONARIO CONT_TALONARIO { get; set; }
        public virtual CONT_TIPOCONCEPTOPAGO CONT_TIPOCONCEPTOPAGO { get; set; }
        public virtual ICollection<CONT_FACTURA> CONT_FACTURA { get; set; }
    }
}
