//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SICIApp.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class DATOSPERSONALE
    {
        public string ID { get; set; }
        public string PRIMERNOMBRE { get; set; }
        public string SEGUNDONOMBRE { get; set; }
        public string PRIMERAPELLIDO { get; set; }
        public string SEGUNDOAPELLIDO { get; set; }
        public string PROFESION { get; set; }
        public string NUMEROIDENTIDAD { get; set; }
        public Nullable<bool> EXTRANJERO { get; set; }
        public string NUMEROPASAPORTE { get; set; }
        public string FOTOGRAFIA { get; set; }
        public Nullable<int> IDCIUDADORIGEN { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual CITY CITY { get; set; }
    }
}
