//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SICIApp.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class DATOSPROBLEMADROGAS_CONSUMODROGAS
    {
        public int ID { get; set; }
        public Nullable<int> IDINGRESO { get; set; }
        public Nullable<int> IDDROGA { get; set; }
    
        public virtual DATOSPROBLEMADROGAS_DROGAS DATOSPROBLEMADROGAS_DROGAS { get; set; }
        public virtual INGRESO INGRESO { get; set; }
    }
}
