//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SICIApp.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class DATOSPERSONALES1
    {
        public int IDPERSONA { get; set; }
        public string DIRECCIONDOMICILIO { get; set; }
        public string TELEFONOFIJO { get; set; }
        public string TELEFONOMOVIL { get; set; }
        public string LUGARNACIMIENTO { get; set; }
        public Nullable<System.DateTime> FECHANACIMIENTO { get; set; }
        public string ESTADOCIVIL { get; set; }
        public Nullable<int> NUMERODEHIJOS { get; set; }
        public string NOMBREMADRE { get; set; }
        public Nullable<bool> VIVECONMADRE { get; set; }
        public string NOMBREPADRE { get; set; }
        public Nullable<bool> VIVECONPADRE { get; set; }
        public string CONQUIENVIVE { get; set; }
        public Nullable<int> NUMEROHERMANOS { get; set; }
        public Nullable<int> IDCIUDADNATAL { get; set; }
        public Nullable<int> IDCIUDADRESIDENCIAACTUAL { get; set; }
        public string IDPAISNACIONALIDAD { get; set; }
    
        public virtual CITY CITY { get; set; }
        public virtual CITY CITY1 { get; set; }
        public virtual COUNTRY COUNTRY { get; set; }
        public virtual FICHA FICHA { get; set; }
    }
}
