//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SICIApp.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class DATOSPROBLEMADROGAS_DROGAS
    {
        public DATOSPROBLEMADROGAS_DROGAS()
        {
            this.DATOSPROBLEMADROGAS_CONSUMODROGAS = new HashSet<DATOSPROBLEMADROGAS_CONSUMODROGAS>();
        }
    
        public int ID { get; set; }
        public string NOMBRECIENTIFICO { get; set; }
        public string NOMBRECOMUN { get; set; }
        public string DESCRIPCION { get; set; }
    
        public virtual ICollection<DATOSPROBLEMADROGAS_CONSUMODROGAS> DATOSPROBLEMADROGAS_CONSUMODROGAS { get; set; }
    }
}
