//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SICIApp.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class DATOSPROBLEMADROGAS_CONSUMO
    {
        public int IDINGRESO { get; set; }
        public Nullable<int> EDADCOMIENZO { get; set; }
        public Nullable<bool> INTENTODEJARLAS { get; set; }
        public Nullable<bool> PROBLEMAFISICO { get; set; }
        public Nullable<bool> PROBLEMAMENTAL { get; set; }
        public Nullable<bool> TRATAMIENTOMEDICO { get; set; }
        public Nullable<System.DateTime> FECHADIAGNOSTICO { get; set; }
        public string EXPLIQUEPROBLEMAS { get; set; }
        public string LUGARTRATAMIENTO { get; set; }
        public Nullable<int> ANIOTRATAMIENTO { get; set; }
        public Nullable<int> ABSTINENCIADIAS { get; set; }
        public Nullable<int> ABSTINENCIASEMANAS { get; set; }
        public Nullable<int> ABSTINENCIAMESES { get; set; }
    
        public virtual INGRESO INGRESO { get; set; }
    }
}
