//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SICIApp.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class DOCUMENTOSINGRESO
    {
        public int ID { get; set; }
        public string NOMBRE { get; set; }
        public string RUTA { get; set; }
        public Nullable<System.DateTime> FECHACARGADO { get; set; }
        public Nullable<int> IDINGRESO { get; set; }
        public Nullable<int> IDTIPODOCUMENTO { get; set; }
    
        public virtual INGRESO INGRESO { get; set; }
        public virtual TIPOSDOCUMENTO TIPOSDOCUMENTO { get; set; }
    }
}
