//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SICIApp.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class EXAMENPSICOMETRICO_INTERNOCALIFICACIONES
    {
        public int ID { get; set; }
        public Nullable<int> IDINGRESO { get; set; }
        public Nullable<int> IDPREGUNTA { get; set; }
        public Nullable<int> CALIFICACIONOBTENIDA { get; set; }
    
        public virtual EXAMENPSICOMETRICO_EXAMENCONTENIDO EXAMENPSICOMETRICO_EXAMENCONTENIDO { get; set; }
        public virtual INGRESO INGRESO { get; set; }
    }
}
