//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SICIApp.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class EXAMENPSICOMETRICO_EXAMENCONTENIDO
    {
        public EXAMENPSICOMETRICO_EXAMENCONTENIDO()
        {
            this.EXAMENPSICOMETRICO_INTERNOCALIFICACIONES = new HashSet<EXAMENPSICOMETRICO_INTERNOCALIFICACIONES>();
        }
    
        public int IDPREGUNTA { get; set; }
        public string DETALLE { get; set; }
        public Nullable<int> VALORACION { get; set; }
        public string DESCRIPCION { get; set; }
        public Nullable<int> IDEXAMEN { get; set; }
    
        public virtual EXAMENPSICOMETRICO_EXAMEN EXAMENPSICOMETRICO_EXAMEN { get; set; }
        public virtual ICollection<EXAMENPSICOMETRICO_INTERNOCALIFICACIONES> EXAMENPSICOMETRICO_INTERNOCALIFICACIONES { get; set; }
    }
}
