//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SICIApp.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class EXAMENPSICOMETRICO_EXAMEN
    {
        public EXAMENPSICOMETRICO_EXAMEN()
        {
            this.EXAMENPSICOMETRICO_EXAMENCONTENIDO = new HashSet<EXAMENPSICOMETRICO_EXAMENCONTENIDO>();
        }
    
        public int IDEXAMEN { get; set; }
        public string TITULO { get; set; }
        public string DESCRIPCION { get; set; }
        public string ARCHIVOFISOCO { get; set; }
    
        public virtual ICollection<EXAMENPSICOMETRICO_EXAMENCONTENIDO> EXAMENPSICOMETRICO_EXAMENCONTENIDO { get; set; }
    }
}
