//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SICIApp.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class FICHA
    {
        public FICHA()
        {
            this.INGRESO = new HashSet<INGRESO>();
        }
    
        public int ID { get; set; }
        public string NUMEROIDENTIDAD { get; set; }
        public string NUMEROPASAPORTE { get; set; }
        public string PRIMERNOMBRE { get; set; }
        public string SEGUNDONOMBRE { get; set; }
        public string PRIMERAPELLIDO { get; set; }
        public string SEGUNDOAPELLIDO { get; set; }
        public string NACIONALIDAD { get; set; }
    
        public virtual ICollection<INGRESO> INGRESO { get; set; }
        public virtual DATOSPERSONALES1 DATOSPERSONALES1 { get; set; }
    }
}
