//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SICIApp.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class INFORMACIONACADEMICA_OFICIOS
    {
        public INFORMACIONACADEMICA_OFICIOS()
        {
            this.INFORMACIONACADEMICA_ESTUDIOSOFICIO = new HashSet<INFORMACIONACADEMICA_ESTUDIOSOFICIO>();
        }
    
        public int ID { get; set; }
        public string NOMBREOFICIO { get; set; }
        public string DESCRIPCIONOFICIO { get; set; }
    
        public virtual ICollection<INFORMACIONACADEMICA_ESTUDIOSOFICIO> INFORMACIONACADEMICA_ESTUDIOSOFICIO { get; set; }
    }
}
