//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SICIApp.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class INFORMACIONACADEMICA_ESCOLARIDAD
    {
        public INFORMACIONACADEMICA_ESCOLARIDAD()
        {
            this.INFORMACIONACADEMICA_ESTUDIOSESCOLARIDAD = new HashSet<INFORMACIONACADEMICA_ESTUDIOSESCOLARIDAD>();
        }
    
        public int ID { get; set; }
        public string NOMBREESCOLARIDAD { get; set; }
        public string DESCRIPCIONESCOLARIDAD { get; set; }
    
        public virtual ICollection<INFORMACIONACADEMICA_ESTUDIOSESCOLARIDAD> INFORMACIONACADEMICA_ESTUDIOSESCOLARIDAD { get; set; }
    }
}
