//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SICIApp.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class INGRESO
    {
        public INGRESO()
        {
            this.APARATOSSISTEMAS = new HashSet<APARATOSSISTEMAS>();
            this.EVALUACIONMEDICADETALLE = new HashSet<EVALUACIONMEDICADETALLE>();
            this.EXAMENPSICOMETRICO_INTERNOCALIFICACIONES = new HashSet<EXAMENPSICOMETRICO_INTERNOCALIFICACIONES>();
            this.CAUSASEGRESOINTERNO = new HashSet<CAUSASEGRESOINTERNO>();
            this.CONDICIONFISICA_INTERNOENFERMEDADES = new HashSet<CONDICIONFISICA_INTERNOENFERMEDADES>();
            this.DATOSPROBLEMADROGAS_CONSUMODROGAS = new HashSet<DATOSPROBLEMADROGAS_CONSUMODROGAS>();
            this.DOCUMENTOSINGRESO = new HashSet<DOCUMENTOSINGRESO>();
            this.CENTRODESARROLLOINGRESO = new HashSet<CENTRODESARROLLOINGRESO>();
        }
    
        public int ID { get; set; }
        public string NUMEXPEDIENTE { get; set; }
        public Nullable<System.DateTime> FECHAUTORIZACION { get; set; }
        public Nullable<System.DateTime> FECHAFIRMAACUERDO { get; set; }
        public Nullable<System.DateTime> FECHAREALINGRESOPV { get; set; }
        public Nullable<System.DateTime> FECHAEGRESOPV { get; set; }
        public Nullable<System.DateTime> FECHAINGRESOSISTEMA { get; set; }
        public string OBSERVACIONES { get; set; }
        public string CONTRATO { get; set; }
        public Nullable<int> IDPERSONA { get; set; }
        public Nullable<bool> ACEPTADO { get; set; }
        public Nullable<int> STATUSFLOW { get; set; }
    
        public virtual ICollection<APARATOSSISTEMAS> APARATOSSISTEMAS { get; set; }
        public virtual ICollection<EVALUACIONMEDICADETALLE> EVALUACIONMEDICADETALLE { get; set; }
        public virtual SIGNOSVITALES SIGNOSVITALES { get; set; }
        public virtual DATOSSOCIOECONOMICOS DATOSSOCIOECONOMICOS { get; set; }
        public virtual ESTADOMENTAL ESTADOMENTAL { get; set; }
        public virtual EXAMENPSICOMETRICO EXAMENPSICOMETRICO { get; set; }
        public virtual ICollection<EXAMENPSICOMETRICO_INTERNOCALIFICACIONES> EXAMENPSICOMETRICO_INTERNOCALIFICACIONES { get; set; }
        public virtual HISTORIALPERSONALFAMILIAR HISTORIALPERSONALFAMILIAR { get; set; }
        public virtual IMPRESIONDIAGNOSTICA IMPRESIONDIAGNOSTICA { get; set; }
        public virtual OBERVACIONPRELIMINAR OBERVACIONPRELIMINAR { get; set; }
        public virtual RECOMENDACIONES RECOMENDACIONES { get; set; }
        public virtual ICollection<CAUSASEGRESOINTERNO> CAUSASEGRESOINTERNO { get; set; }
        public virtual CONDICIONFISICA_INGRESO CONDICIONFISICA_INGRESO { get; set; }
        public virtual ICollection<CONDICIONFISICA_INTERNOENFERMEDADES> CONDICIONFISICA_INTERNOENFERMEDADES { get; set; }
        public virtual DATOSDELICTIVOS DATOSDELICTIVOS { get; set; }
        public virtual DATOSPROBLEMADROGAS_CONSUMO DATOSPROBLEMADROGAS_CONSUMO { get; set; }
        public virtual ICollection<DATOSPROBLEMADROGAS_CONSUMODROGAS> DATOSPROBLEMADROGAS_CONSUMODROGAS { get; set; }
        public virtual INFORMACIONACADEMICA_ESTUDIOS INFORMACIONACADEMICA_ESTUDIOS { get; set; }
        public virtual FICHA FICHA { get; set; }
        public virtual MOTIVOSINGRESO MOTIVOSINGRESO { get; set; }
        public virtual ICollection<DOCUMENTOSINGRESO> DOCUMENTOSINGRESO { get; set; }
        public virtual ICollection<CENTRODESARROLLOINGRESO> CENTRODESARROLLOINGRESO { get; set; }
    }
}
