//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SICIApp.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRO_CABANIA
    {
        public PRO_CABANIA()
        {
            this.PRO_CABANIADESARROLLO = new HashSet<PRO_CABANIADESARROLLO>();
        }
    
        public int ID { get; set; }
        public string NOMBRE { get; set; }
        public string DESCRIPCION { get; set; }
        public Nullable<int> CAPACIDAD { get; set; }
        public Nullable<double> GEOLAT { get; set; }
        public Nullable<double> GEOLONG { get; set; }
        public Nullable<bool> ACTIVO { get; set; }
        public string IDCENTROTERAPEUTICO { get; set; }
        public Nullable<int> IDNIVEL { get; set; }
        public string USUARIO { get; set; }
    
        public virtual CENTROTERAPEUTICO CENTROTERAPEUTICO { get; set; }
        public virtual PRO_NIVEL PRO_NIVEL { get; set; }
        public virtual ICollection<PRO_CABANIADESARROLLO> PRO_CABANIADESARROLLO { get; set; }
    }
}
