//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SICIApp.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRO_NIVELCRITERIO
    {
        public int ID { get; set; }
        public Nullable<int> IDCRITERIO { get; set; }
        public Nullable<int> IDNIVEL { get; set; }
    
        public virtual PRO_CRITERIO PRO_CRITERIO { get; set; }
        public virtual PRO_NIVEL PRO_NIVEL { get; set; }
    }
}
