//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SICIApp.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRO_PROMOCIONNIVEL
    {
        public int ID { get; set; }
        public Nullable<int> IDINGRESO { get; set; }
        public Nullable<int> IDNIVEL { get; set; }
        public Nullable<System.DateTime> FECHAPROMOCION { get; set; }
        public Nullable<System.DateTime> FECHACLAUSURA { get; set; }
        public string URLDIPLOMA { get; set; }
        public string OBSERVACIONES { get; set; }
        public Nullable<System.DateTime> FECHAREGISTRO { get; set; }
        public string USUARIO { get; set; }
        public string MONITORRESPONSABLE { get; set; }
        public Nullable<decimal> CALIFICACION { get; set; }
        public string ESTADO { get; set; }
    
        public virtual INGRESO INGRESO { get; set; }
        public virtual PRO_NIVEL PRO_NIVEL { get; set; }
    }
}
