//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SICIApp.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRO_CABANIADESARROLLO
    {
        public int ID { get; set; }
        public int IDCTDESARROLLO { get; set; }
        public Nullable<int> IDCABANIA { get; set; }
        public Nullable<bool> ACTIVO { get; set; }
        public Nullable<System.DateTime> FECHAINGRESO { get; set; }
        public Nullable<System.DateTime> FECHAEGRESO { get; set; }
        public string USUARIO { get; set; }
    
        public virtual CENTRODESARROLLOINGRESO CENTRODESARROLLOINGRESO { get; set; }
        public virtual PRO_CABANIA PRO_CABANIA { get; set; }
    }
}
