//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SICIApp.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRO_NIVEL
    {
        public PRO_NIVEL()
        {
            this.PRO_NIVELCRITERIO = new HashSet<PRO_NIVELCRITERIO>();
            this.PRO_PROMOCIONNIVEL = new HashSet<PRO_PROMOCIONNIVEL>();
        }
    
        public int ID { get; set; }
        public string NOMBRE { get; set; }
        public string DESCRIPCION { get; set; }
        public Nullable<int> DIASESTIMADOS { get; set; }
        public Nullable<int> IDFASE { get; set; }
    
        public virtual PRO_FASE PRO_FASE { get; set; }
        public virtual ICollection<PRO_NIVELCRITERIO> PRO_NIVELCRITERIO { get; set; }
        public virtual ICollection<PRO_PROMOCIONNIVEL> PRO_PROMOCIONNIVEL { get; set; }
    }
}
