//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SICIApp.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TER_RESUMENEVOLUCION
    {
        public int ID { get; set; }
        public Nullable<int> IDINGRESO { get; set; }
        public Nullable<int> IDCATEGORIAAREA { get; set; }
        public Nullable<System.DateTime> FECHAULTIMAACTUALIZACION { get; set; }
        public Nullable<System.DateTime> FECHAREGISTRO { get; set; }
        public string INICIOPROCESO { get; set; }
        public string DURANTEPROCESO { get; set; }
        public string FINPROCESO { get; set; }
        public string PXSISTFAMILIAR { get; set; }
        public string USUARIO { get; set; }
    
        public virtual INGRESO INGRESO { get; set; }
        public virtual TER_CATEGORIAAREA TER_CATEGORIAAREA { get; set; }
    }
}
