//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SICIApp.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TER_EXAMENPERSONALIDAD
    {
        public TER_EXAMENPERSONALIDAD()
        {
            this.TER_ASPECTOEXAMENPERSONALIDAD = new HashSet<TER_ASPECTOEXAMENPERSONALIDAD>();
        }
    
        public int ID { get; set; }
        public Nullable<int> IDINGRESO { get; set; }
        public Nullable<decimal> CALIFICAIONTOTAL { get; set; }
        public string OBSERVACIONES { get; set; }
        public string PERSONALIADDOMINANTE { get; set; }
        public string PERSONALIDADSEGUNDA { get; set; }
    
        public virtual INGRESO INGRESO { get; set; }
        public virtual ICollection<TER_ASPECTOEXAMENPERSONALIDAD> TER_ASPECTOEXAMENPERSONALIDAD { get; set; }
    }
}
