//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SICIApp.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TER_CATEGORIAAREA
    {
        public TER_CATEGORIAAREA()
        {
            this.TER_CRITERIOCALIFICACION = new HashSet<TER_CRITERIOCALIFICACION>();
            this.TER_INCIDENCIAAREA = new HashSet<TER_INCIDENCIAAREA>();
            this.TER_RESUMENEVOLUCION = new HashSet<TER_RESUMENEVOLUCION>();
        }
    
        public int ID { get; set; }
        public string NOMBRE { get; set; }
        public string DESCRIPCION { get; set; }
    
        public virtual ICollection<TER_CRITERIOCALIFICACION> TER_CRITERIOCALIFICACION { get; set; }
        public virtual ICollection<TER_INCIDENCIAAREA> TER_INCIDENCIAAREA { get; set; }
        public virtual ICollection<TER_RESUMENEVOLUCION> TER_RESUMENEVOLUCION { get; set; }
    }
}
