//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SICIApp.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TER_CATEGORIAASPECTOCARCTER
    {
        public TER_CATEGORIAASPECTOCARCTER()
        {
            this.TER_ACTITUD = new HashSet<TER_ACTITUD>();
        }
    
        public int ID { get; set; }
        public string NOMBRE { get; set; }
        public string DESCRIPCION { get; set; }
    
        public virtual ICollection<TER_ACTITUD> TER_ACTITUD { get; set; }
    }
}
