//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SICIApp.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TER_CALIFAREA
    {
        public TER_CALIFAREA()
        {
            this.TER_AREACRITERIOCALIF = new HashSet<TER_AREACRITERIOCALIF>();
        }
    
        public int ID { get; set; }
        public string NOMBRE { get; set; }
        public string OBSERVACIONES { get; set; }
        public Nullable<decimal> CALIFICACIONTOTAL { get; set; }
        public Nullable<int> IDINGRESO { get; set; }
    
        public virtual INGRESO INGRESO { get; set; }
        public virtual ICollection<TER_AREACRITERIOCALIF> TER_AREACRITERIOCALIF { get; set; }
    }
}
