//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SICIApp.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TER_INCIDENCIAAREA
    {
        public int ID { get; set; }
        public Nullable<int> IDINGRESO { get; set; }
        public Nullable<int> IDCATEGORIAAREA { get; set; }
        public Nullable<System.DateTime> FECHADUAGNOSTICO { get; set; }
        public string MONITOR { get; set; }
        public string MOTIVOVISITA { get; set; }
        public string DETALLEGENRAL { get; set; }
        public string ACTITUDESMOSTRADAS { get; set; }
        public string RECOMENDACIONES { get; set; }
        public string EXPLICACIONCONDUCTA { get; set; }
        public string PSICOTERAPIA { get; set; }
        public string PRONOSTICO { get; set; }
        public Nullable<bool> ACTITUD { get; set; }
        public string ACCIONREALIZADA { get; set; }
        public string OBSERVACIONEXTRA { get; set; }
        public string USUARIO { get; set; }
        public Nullable<System.DateTime> FECHAREGISTRO { get; set; }
    
        public virtual INGRESO INGRESO { get; set; }
        public virtual TER_CATEGORIAAREA TER_CATEGORIAAREA { get; set; }
    }
}
