//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SICIApp.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TER_ASPECTOPERSONALIDAD
    {
        public TER_ASPECTOPERSONALIDAD()
        {
            this.TER_ASPECTOEXAMENPERSONALIDAD = new HashSet<TER_ASPECTOEXAMENPERSONALIDAD>();
        }
    
        public int ID { get; set; }
        public string NOMBRE { get; set; }
        public string DESCRIPCION { get; set; }
        public Nullable<int> CALIFICACIONESPERADA { get; set; }
        public Nullable<int> IDCATEGORIAPERSONALIDAD { get; set; }
    
        public virtual ICollection<TER_ASPECTOEXAMENPERSONALIDAD> TER_ASPECTOEXAMENPERSONALIDAD { get; set; }
        public virtual TER_CATEGORIAPERSONALIDAD TER_CATEGORIAPERSONALIDAD { get; set; }
    }
}
