//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SICIApp.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TER_MATRICULA
    {
        public int ID { get; set; }
        public Nullable<int> IDCURSO { get; set; }
        public Nullable<int> IDINSTRUCTOR { get; set; }
        public Nullable<int> IDINGRESO { get; set; }
        public Nullable<int> CALIFICACIONTOTAL { get; set; }
        public string OBSERVACIONES { get; set; }
        public string NOMBREMATRICULA { get; set; }
        public Nullable<System.DateTime> FECHAINICIO { get; set; }
        public Nullable<System.DateTime> FECHACLAUSURA { get; set; }
        public string DIAS { get; set; }
        public Nullable<System.TimeSpan> HORAINICIO { get; set; }
        public Nullable<System.TimeSpan> HORAFIN { get; set; }
        public string URLCERTIFICADO { get; set; }
        public string ESTADO { get; set; }
    
        public virtual INGRESO INGRESO { get; set; }
        public virtual TER_CURSO TER_CURSO { get; set; }
        public virtual TER_INSTRUCTOR TER_INSTRUCTOR { get; set; }
    }
}
