//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SICIApp.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TER_EVALUACIONCARACTER
    {
        public int ID { get; set; }
        public Nullable<int> IDACTITUD { get; set; }
        public Nullable<int> IDINGRESO { get; set; }
        public Nullable<decimal> CALIFICACION { get; set; }
    
        public virtual INGRESO INGRESO { get; set; }
        public virtual TER_ACTITUD TER_ACTITUD { get; set; }
    }
}
