//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SICIApp.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TER_FALTA
    {
        public int ID { get; set; }
        public Nullable<int> IDCATEGORIAFALTA { get; set; }
        public Nullable<int> IDINGRESO { get; set; }
        public string DESCRIPCION { get; set; }
        public Nullable<System.DateTime> FECHAAPLICADA { get; set; }
        public string MONITOR { get; set; }
        public string USUARIO { get; set; }
    
        public virtual INGRESO INGRESO { get; set; }
        public virtual TER_CATEGORIAFALTA TER_CATEGORIAFALTA { get; set; }
    }
}
