//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SICIApp.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class USUARIOCENTROCONSULTA
    {
        public int ID { get; set; }
        public string IDCT { get; set; }
        public string IDUSUARIO { get; set; }
        public Nullable<System.DateTime> FECHACREACION { get; set; }
        public Nullable<bool> ACTIVO { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual CENTROTERAPEUTICO CENTROTERAPEUTICO { get; set; }
    }
}
