/*
  Reporte de calificaci�n de la cartera
  
  
   
   Reporte de Operaciones canceladas al mes de 
  
             BANDERA PARA FECHA DE INICIO = '20150701'
             BANDERA PARA FECHA DE FIN = '20150706'

             BANDERA PARA MES DE ACTUAL = 7
             BANDERA PARA FECHA CIERRE MES ANTERIOR = '20150630'
             BANDERA PARA ANIO ACTUAL = 2015'

*/


declare @fecha as datetime
set @fecha='20150706'
SELECT
OFI.SECUENCIAL SECUENCIALOFICINA, OFI.NOMBRE OFICINA,
U.NOMBRE USUARIOASESOR,
C.NUMEROCLIENTE, RTRIM(P.IDENTIFICACION) IDENTIFICACION, P.NOMBREUNIDO,
ACT.NOMBRE ACTIVIDAD, TV.NOMBRE AS ESTADO,
(SELECT TI.NOMBRE
FROM FBS_GENERALES.ACTIVIDADECONOMICA AE
INNER JOIN FBS_GENERALES.DIVISION_ACTIECONTIPOINDUSTRIA AETI ON AETI.SECUENCIALACTIVIDADECONOMICA = AE.SECUENCIALDIVISION
INNER JOIN FBS_GENERALES.TIPOINDUSTRIA TI ON TI.CODIGO = AETI.CODIGOTIPOINDUSTRIA
WHERE AE.SECUENCIALDIVISION = P.SECUENCIALDIVISIONACTIVIDECON) SECTOR,
PM.NUMEROPRESTAMO NUMEROLIQUIDACION, TM.CODIGO METODOLOGIA,
O.CODIGOOFICINACONTROL CODIGOOFICINA,
CASE WHEN PM.ESREFINANCIAMIENTO = 1 THEN 
	'REFINANCIAMIENTO'
ELSE CASE WHEN PM.ESREADECUACION = 1 THEN
		'READECUACION'
	ELSE TG.NOMBRE END END TIPOGARANTIA,
(SELECT SCC.CODIGO
FROM FBS_CREDITO.SEGMENTOINTERNO SI
INNER JOIN FBS_CREDITO.CLASIFICSUBCLASIFICACIONCREDIT CSCC ON CSCC.SECUENCIAL = SI.SECUENCIALCLASSUBCLASIFICACION
INNER JOIN FBS_CREDITO.SUBCLASIFICACIONCREDITO SCC ON SCC.CODIGO = CSCC.CODIGOSUBCLASIFICACIONCREDITO
WHERE SI.SECUENCIAL = PM.SECUENCIALSEGMENTOINTERNO) CLASIFICACION,
TP.SIGLAS TIPOPRESTAMO,
CCP.LETRACALIFICACION,
CP.SALDOPRESTAMO,
CP.TOTALINTERES,
CP.DIASMOROSIDADCAPITAL,
CP.DIASMOROSIDADINTERES, 
CP.PROVISIONAUTOMATICACAPITAL,
CP.PROVISIONAUTOMATICAINTERES,
CCP.PORCENTAJEFIJO,
CP.FECHACALIFICACION,
PM.FRECUENCIAPAGO,

ISNULL((SELECT PCC.VALORPROYECTADO
		FROM FBS_CARTERA.PRESTAMOCOMPONENTE_CARTERA PCC
		INNER JOIN FBS_CARTERA.COMPONENTE_CARTERA_CAPITAL CCC ON CCC.SECUENCIALCOMPONENTECARTERA = PCC.SECUENCIALCOMPONENTECARTERA
		WHERE PCC.SECUENCIALPRESTAMO = PM.SECUENCIAL
		AND PCC.NUMEROCUOTA = PPCP.NUMEROCUOTA),0) VALORCUOTAPROXIMA,

PM.FECHAVENCIMIENTO

FROM FBS_CARTERA.CALIFICACIONPRESTAMO CP
INNER JOIN FBS_CARTERA.CONDICIONCALIFICACIONPRESTAMO CCP ON CCP.SECUENCIAL = CP.SECUENCIALCONDICIONCALIFAUT

INNER JOIN (SELECT *
            FROM FBS_HISTORICOS.FBS_HISTORICOS.PRESTAMOMAESTRO PM1
            WHERE @fecha BETWEEN PM1.FECHAHISTORICO AND PM1.FECHAMODIFICA)  PM ON PM.SECUENCIAL = CP.SECUENCIALPRESTAMO

INNER JOIN FBS_CREDITO.TIPOGARANTIA TG ON TG.CODIGO = CODIGOTIPOGARANTIA
INNER JOIN FBS_CARTERA.PRESTAMOCLIENTE PC ON PC.SECUENCIALPRESTAMO = PM.SECUENCIAL
INNER JOIN FBS_CLIENTES.CLIENTE C ON C.SECUENCIAL = PC.SECUENCIALCLIENTE
INNER JOIN FBS_PERSONAS.PERSONA P ON P.SECUENCIAL = C.SECUENCIALPERSONA

INNER JOIN FBS_CREDITO.TIPOMETODOLOGIA TM ON TM.CODIGO = PM.CODIGOTIPOMETODOLOGIA
INNER JOIN FBS_CARTERA.TIPOVENCIMIENTO TV ON TV.SECUENCIAL = PM.SECUENCIALTIPOVENCIMIENTO

INNER JOIN FBS_CREDITO.TIPOPRESTAMO TP ON PM.CODIGOTIPOPRESTAMO = TP.CODIGO
INNER JOIN FBS_CARTERA.ESTADOPRESTAMO EP ON PM.CODIGOESTADOPRESTAMO = EP.CODIGO
INNER JOIN FBS_ORGANIZACIONES.OFICINA O ON O.SECUENCIALDIVISION = PM.SECUENCIALOFICINA
INNER JOIN FBS_GENERALES.DIVISION OFI ON O.SECUENCIALDIVISION = OFI.SECUENCIAL

INNER JOIN FBS_SEGURIDADES.USUARIO U ON U.CODIGO = PM.CODIGOUSUARIOOFICIAL
INNER JOIN FBS_GENERALES.DIVISION ACT ON ACT.SECUENCIAL = P.SECUENCIALDIVISIONACTIVIDECON

LEFT JOIN (SELECT PCC.SECUENCIALPRESTAMO, MIN(PCC.NUMEROCUOTA) NUMEROCUOTA
           FROM FBS_HISTORICOS.FBS_HISTORICOS.PRESTAMOCOMPONENTE_CARTERA PCC
           INNER JOIN FBS_CARTERA.COMPONENTE_CARTERA_CAPITAL CCC ON CCC.SECUENCIALCOMPONENTECARTERA = PCC.SECUENCIALCOMPONENTECARTERA
		   WHERE @fecha BETWEEN PCC.FECHAHISTORICO AND PCC.FECHAMODIFICA
		   AND PCC.FECHAINICIO >= @fecha
		   GROUP BY PCC.SECUENCIALPRESTAMO) PPCP ON PPCP.SECUENCIALPRESTAMO = PM.SECUENCIAL

WHERE CP.FECHACALIFICACION = @fecha
